const crypto = require('crypto');
const supabase = require('../config/db');

const dbError = (res, error) => res.status(error?.code === '23505' ? 409 : 400).json({ message: error?.message || 'Database operation failed' });
async function ownedExam(examId, userId) { return supabase.from('exams').select('*, courses!exams_course_id_fkey(teacher_id)').eq('id', examId).maybeSingle(); }
async function isAdmin(userId) { const { data } = await supabase.from('profiles').select('role').eq('id', userId).maybeSingle(); return String(data?.role || '').toLowerCase() === 'admin'; }

const getCourseExam = async (req, res, next) => {
  try {
    const { data: exam, error } = await supabase.from('exams').select('*').eq('course_id', req.params.courseId).eq('status', 'active').maybeSingle();
    if (error) return dbError(res, error); if (!exam) return res.status(404).json({ message: 'Active exam not found' });
    const { data: course } = await supabase.from('courses').select('teacher_id').eq('id', exam.course_id).single();
    const teacher = course.teacher_id === req.user.id;
    const { data: enrollment } = teacher ? { data: null } : await supabase.from('course_enrollments').select('exam_state, status').eq('course_id', exam.course_id).eq('learner_id', req.user.id).maybeSingle();
    if (!teacher && (!enrollment || enrollment.status !== 'active' || !['eligible', 'scheduled'].includes(enrollment.exam_state))) return res.status(403).json({ message: 'You are not eligible to take this exam' });
    const { data: questions, error: questionError } = await supabase.from('exam_questions').select('id, question_text, options, order, correct_option_idx').eq('exam_id', exam.id).order('order');
    if (questionError) return dbError(res, questionError);
    return res.json({ ...exam, questions: questions.map((q) => teacher ? q : ({ id: q.id, questionText: q.question_text, options: q.options, order: q.order })) });
  } catch (error) { return next(error); }
};
const createExam = async (req, res, next) => {
  try { const { data: course } = await supabase.from('courses').select('id').eq('id', req.params.courseId).eq('teacher_id', req.user.id).maybeSingle(); if (!course) return res.status(403).json({ message: 'Only the course teacher can manage exams' }); const b = req.body; const { data, error } = await supabase.from('exams').insert({ course_id: course.id, title: b.title, description: b.description || null, time_limit_mins: b.timeLimitMins || 0, pass_mark_percentage: b.passMarkPercentage ?? 70, status: b.status || 'inactive' }).select().single(); if (error) return dbError(res, error); return res.status(201).json(data); } catch (error) { return next(error); }
};
const updateExam = async (req, res, next) => {
  try { const { data: exam } = await ownedExam(req.params.examId, req.user.id); if (!exam) return res.status(403).json({ message: 'Exam not found or not owned by you' }); if (exam.courses.teacher_id !== req.user.id) return res.status(403).json({ message: 'Only the course teacher can manage exams' }); const b = req.body; const updates = {}; [['title', 'title'], ['description', 'description'], ['timeLimitMins', 'time_limit_mins'], ['passMarkPercentage', 'pass_mark_percentage'], ['status', 'status']].forEach(([from, to]) => { if (b[from] !== undefined) updates[to] = b[from]; }); const { data, error } = await supabase.from('exams').update(updates).eq('id', exam.id).select().single(); if (error) return dbError(res, error); return res.json(data); } catch (error) { return next(error); }
};
const addQuestion = async (req, res, next) => {
  try { const { data: exam } = await ownedExam(req.params.examId, req.user.id); if (!exam) return res.status(403).json({ message: 'Exam not found or not owned by you' }); if (exam.courses.teacher_id !== req.user.id) return res.status(403).json({ message: 'Only the course teacher can manage questions' }); const b = req.body; const { data, error } = await supabase.from('exam_questions').insert({ exam_id: exam.id, question_text: b.questionText, options: b.options, correct_option_idx: b.correctOptionIdx, order: b.order }).select().single(); if (error) return dbError(res, error); return res.status(201).json(data); } catch (error) { return next(error); }
};
const submitExam = async (req, res, next) => {
  try {
    const { data: exam, error } = await supabase.from('exams').select('*').eq('id', req.params.examId).eq('status', 'active').maybeSingle(); if (error) return dbError(res, error); if (!exam) return res.status(404).json({ message: 'Active exam not found' });
    const { data: enrollment } = await supabase.from('course_enrollments').select('*').eq('course_id', exam.course_id).eq('learner_id', req.user.id).maybeSingle();
    if (!enrollment || enrollment.status !== 'active' || !['eligible', 'scheduled'].includes(enrollment.exam_state)) return res.status(403).json({ message: 'You are not eligible to submit this exam' });
    const { data: prior } = await supabase.from('exam_attempts').select('id').eq('exam_id', exam.id).eq('learner_id', req.user.id).eq('status', 'passed').limit(1);
    if (prior?.length) return res.status(409).json({ message: 'A passing attempt already exists' });
    const { data: questions, error: questionError } = await supabase.from('exam_questions').select('id, correct_option_idx, options').eq('exam_id', exam.id).order('order'); if (questionError) return dbError(res, questionError); if (!questions.length) return res.status(409).json({ message: 'This exam has no questions' });
    const submitted = req.body.answers; const answers = questions.map((question, index) => Array.isArray(submitted) ? submitted[index] : submitted[question.id]);
    if (answers.some((answer, i) => answer !== null && (answer < 0 || answer >= questions[i].options.length))) return res.status(400).json({ message: 'One or more answers are invalid' });
    const correct = answers.reduce((total, answer, index) => total + (answer === questions[index].correct_option_idx ? 1 : 0), 0); const score = Number(((correct / questions.length) * 100).toFixed(2)); const passed = score >= Number(exam.pass_mark_percentage);
    const { data: attempt, error: insertError } = await supabase.from('exam_attempts').insert({ exam_id: exam.id, learner_id: req.user.id, answers, score_percentage: score, status: passed ? 'passed' : 'failed' }).select().single(); if (insertError) return dbError(res, insertError);
    const { error: updateError } = await supabase.from('course_enrollments').update({ exam_state: passed ? 'passed' : 'failed', certificate_state: passed ? 'none' : 'none', status: passed ? 'completed' : 'active', completed_at: passed ? new Date().toISOString() : null }).eq('id', enrollment.id); if (updateError) return dbError(res, updateError);
    return res.status(201).json({ id: attempt.id, scorePercentage: score, status: attempt.status, passed });
  } catch (error) { return next(error); }
};
const requestCertificate = async (req, res, next) => {
  try { const { data: enrollment } = await supabase.from('course_enrollments').select('*').eq('course_id', req.params.courseId).eq('learner_id', req.user.id).maybeSingle(); if (!enrollment || enrollment.exam_state !== 'passed') return res.status(403).json({ message: 'A passed course exam is required before requesting a certificate' }); const { data: existing } = await supabase.from('certificate_requests').select('id').eq('course_id', req.params.courseId).eq('learner_id', req.user.id).in('admin_decision', ['pending', 'approved']).limit(1); if (existing?.length) return res.status(409).json({ message: 'A certificate request already exists' }); const { data: attempt } = await supabase.from('exam_attempts').select('score_percentage').eq('learner_id', req.user.id).eq('status', 'passed').order('submitted_at', { ascending: false }).limit(1).maybeSingle(); const { data, error } = await supabase.from('certificate_requests').insert({ course_id: req.params.courseId, learner_id: req.user.id, score_snapshot: attempt?.score_percentage || null }).select().single(); if (error) return dbError(res, error); await supabase.from('course_enrollments').update({ certificate_state: 'requested' }).eq('id', enrollment.id); return res.status(201).json(data); } catch (error) { return next(error); }
};
const listCertificateRequests = async (req, res, next) => {
  try { let query = supabase.from('certificate_requests').select('*, course:courses!certificate_requests_course_id_fkey(title, teacher_id), learner:profiles!certificate_requests_learner_id_fkey(id, full_name)'); if (req.query.scope === 'mine') query = query.eq('learner_id', req.user.id); else if (req.query.scope === 'teaching') { const { data: courses } = await supabase.from('courses').select('id').eq('teacher_id', req.user.id); query = query.in('course_id', (courses || []).map((c) => c.id)); } else if (!(await isAdmin(req.user.id))) return res.status(403).json({ message: 'Specify scope=mine or scope=teaching' }); const { data, error } = await query.order('created_at', { ascending: false }); if (error) return dbError(res, error); return res.json(data); } catch (error) { return next(error); }
};
const teacherCertificateDecision = async (req, res, next) => {
  try { const { data: request, error } = await supabase.from('certificate_requests').select('*, courses!certificate_requests_course_id_fkey(teacher_id)').eq('id', req.params.requestId).maybeSingle(); if (error) return dbError(res, error); if (!request) return res.status(404).json({ message: 'Certificate request not found' }); if (request.courses.teacher_id !== req.user.id) return res.status(403).json({ message: 'Only the course teacher may decide this request' }); if (request.tutor_decision !== 'pending') return res.status(409).json({ message: 'Tutor decision already recorded' }); const { data, error: updateError } = await supabase.from('certificate_requests').update({ tutor_decision: req.body.decision, reviewer_id: req.user.id }).eq('id', request.id).select().single(); if (updateError) return dbError(res, updateError); if (req.body.decision === 'rejected') await supabase.from('course_enrollments').update({ certificate_state: 'rejected' }).eq('course_id', request.course_id).eq('learner_id', request.learner_id); return res.json(data); } catch (error) { return next(error); }
};
const adminCertificateDecision = async (req, res, next) => {
  try { const { data: request, error } = await supabase.from('certificate_requests').select('*').eq('id', req.params.requestId).maybeSingle(); if (error) return dbError(res, error); if (!request) return res.status(404).json({ message: 'Certificate request not found' }); if (request.tutor_decision !== 'approved' || request.admin_decision !== 'pending') return res.status(409).json({ message: 'This request is not awaiting admin approval' }); const { data, error: updateError } = await supabase.from('certificate_requests').update({ admin_decision: req.body.decision, reviewer_id: req.user.id }).eq('id', request.id).select().single(); if (updateError) return dbError(res, updateError); if (req.body.decision === 'rejected') { await supabase.from('course_enrollments').update({ certificate_state: 'rejected' }).eq('course_id', request.course_id).eq('learner_id', request.learner_id); return res.json(data); } const certificateNumber = `SS-${new Date().getUTCFullYear()}-${crypto.randomUUID().replace(/-/g, '').slice(0, 12).toUpperCase()}`; const { data: certificate, error: certificateError } = await supabase.from('certificates').insert({ certificate_number: certificateNumber, request_id: request.id, learner_id: request.learner_id, course_id: request.course_id, verification_metadata: { issued_by: req.user.id, score_percentage: request.score_snapshot } }).select().single(); if (certificateError) return dbError(res, certificateError); await supabase.from('course_enrollments').update({ certificate_state: 'issued' }).eq('course_id', request.course_id).eq('learner_id', request.learner_id); return res.json({ request: data, certificate }); } catch (error) { return next(error); }
};
const myCertificates = async (req, res, next) => { try { const { data, error } = await supabase.from('certificates').select('*, course:courses!certificates_course_id_fkey(title, teacher:profiles!courses_teacher_id_fkey(full_name))').eq('learner_id', req.user.id).order('issued_at', { ascending: false }); if (error) return dbError(res, error); return res.json(data); } catch (error) { return next(error); } };
const verifyCertificate = async (req, res, next) => { try { const { data, error } = await supabase.from('certificates').select('certificate_number, issued_at, verification_metadata, learner:profiles!certificates_learner_id_fkey(full_name), course:courses!certificates_course_id_fkey(title, teacher:profiles!courses_teacher_id_fkey(full_name))').eq('certificate_number', req.params.certificateNumber).maybeSingle(); if (error) return dbError(res, error); if (!data) return res.status(404).json({ message: 'Certificate not found' }); return res.json({ valid: true, certificate: data }); } catch (error) { return next(error); } };

module.exports = { getCourseExam, createExam, updateExam, addQuestion, submitExam, requestCertificate, listCertificateRequests, teacherCertificateDecision, adminCertificateDecision, myCertificates, verifyCertificate };
