const supabase = require('../config/db');
const dbError = (res, error) => res.status(error?.code === '23505' ? 409 : 400).json({ message: error?.message || 'Database operation failed' });

async function lectureAccess(lectureId, userId) {
  const { data: lecture, error } = await supabase.from('lectures').select('*, course:courses!lectures_course_id_fkey(teacher_id)').eq('id', lectureId).maybeSingle();
  if (error || !lecture) return { lecture: null, error };
  if (lecture.course.teacher_id === userId) return { lecture, error: null };
  const { data: enrollment, error: enrollmentError } = await supabase.from('course_enrollments').select('id').eq('course_id', lecture.course_id).eq('learner_id', userId).eq('status', 'active').maybeSingle();
  return { lecture: enrollment ? lecture : null, error: enrollmentError };
}
const lectureMessages = async (req, res, next) => { try { const { lecture, error } = await lectureAccess(req.params.lectureId, req.user.id); if (error) return dbError(res, error); if (!lecture) return res.status(403).json({ message: 'Lecture access is required' }); const { data, error: queryError } = await supabase.from('lecture_messages').select('*, sender:profiles!lecture_messages_sender_id_fkey(id, full_name)').eq('lecture_id', lecture.id).order('created_at'); if (queryError) return dbError(res, queryError); return res.json(data); } catch (error) { return next(error); } };
const postLectureMessage = async (req, res, next) => { try { const { lecture, error } = await lectureAccess(req.params.lectureId, req.user.id); if (error) return dbError(res, error); if (!lecture) return res.status(403).json({ message: 'Lecture access is required' }); const { data, error: insertError } = await supabase.from('lecture_messages').insert({ lecture_id: lecture.id, sender_id: req.user.id, body: req.body.body }).select().single(); if (insertError) return dbError(res, insertError); return res.status(201).json(data); } catch (error) { return next(error); } };
const listPosts = async (req, res, next) => { try { const { data, error } = await supabase.from('community_posts').select('*, author:profiles!community_posts_author_id_fkey(id, full_name, username), reactions:post_reactions(reaction_type), comments:post_comments(id)').order('created_at', { ascending: false }); if (error) return dbError(res, error); return res.json(data.map((post) => ({ ...post, reactionCount: post.reactions.length, commentCount: post.comments.length }))); } catch (error) { return next(error); } };
const createPost = async (req, res, next) => { try { const { data, error } = await supabase.from('community_posts').insert({ author_id: req.user.id, content: req.body.content }).select().single(); if (error) return dbError(res, error); return res.status(201).json(data); } catch (error) { return next(error); } };
const toggleReaction = async (req, res, next) => { try { const { data: existing, error } = await supabase.from('post_reactions').select('post_id').eq('post_id', req.params.postId).eq('profile_id', req.user.id).maybeSingle(); if (error) return dbError(res, error); if (existing) { const { error: deleteError } = await supabase.from('post_reactions').delete().eq('post_id', req.params.postId).eq('profile_id', req.user.id); if (deleteError) return dbError(res, deleteError); return res.json({ reacted: false }); } const { error: insertError } = await supabase.from('post_reactions').insert({ post_id: req.params.postId, profile_id: req.user.id, reaction_type: req.body.reactionType }); if (insertError) return dbError(res, insertError); return res.status(201).json({ reacted: true }); } catch (error) { return next(error); } };
module.exports = { lectureMessages, postLectureMessage, listPosts, createPost, toggleReaction };
