import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { zodResolver } from '@hookform/resolvers/zod'
import { useForm } from 'react-hook-form'
import { z } from 'zod'
import { Eye, EyeOff, LockKeyhole, Mail } from 'lucide-react'
import AuthLayout from '../../layouts/AuthLayout'
import { Button, Card } from '../../components/ui'
import { FormField } from '../../components/forms/FormField'
const schema = z.object({ email:z.email('Enter a valid email address'), password:z.string().min(6,'Password must be at least 6 characters'), remember:z.boolean().optional() }); type Data = z.infer<typeof schema>
export default function LoginPage(){ const nav=useNavigate(), [show,setShow]=useState(false), [loading,setLoading]=useState(false); const {register,handleSubmit,formState:{errors}}=useForm<Data>({resolver:zodResolver(schema),defaultValues:{remember:false}}); const submit=()=>{setLoading(true); setTimeout(()=>nav('/admin'),750)}; return <AuthLayout><Card className="w-full max-w-md border-white/60 p-6 shadow-glow sm:p-8"><div className="mb-7"><p className="text-sm font-semibold text-indigo-600">Welcome back</p><h2 className="mt-1 text-3xl font-bold tracking-tight">Sign in to your account</h2><p className="mt-2 text-sm text-slate-500">Continue building your local learning network.</p></div><form onSubmit={handleSubmit(submit)} className="space-y-4"><FormField label="Email address" type="email" placeholder="you@example.com" icon={<Mail size={17}/>} error={errors.email?.message} {...register('email')}/><div><FormField label="Password" type={show?'text':'password'} placeholder="••••••••" icon={<LockKeyhole size={17}/>} error={errors.password?.message} {...register('password')}/><button type="button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)} className="absolute ml-[-2.5rem] mt-[-2.45rem] text-slate-400">{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div><div className="flex items-center justify-between text-sm"><label className="flex cursor-pointer items-center gap-2 text-slate-600"><input type="checkbox" className="h-4 w-4 rounded border-slate-300 text-indigo-600 focus:ring-indigo-500" {...register('remember')}/>Remember me</label><a href="#forgot" className="font-semibold text-indigo-600 hover:text-indigo-700">Forgot password?</a></div><Button loading={loading} className="w-full bg-indigo-600 text-white hover:bg-indigo-700">Sign in</Button></form><div className="my-6 flex items-center gap-3 text-xs text-slate-400"><span className="h-px flex-1 bg-slate-200"/>OR CONTINUE WITH<span className="h-px flex-1 bg-slate-200"/></div><Button className="w-full border border-slate-200 bg-white text-slate-700 hover:bg-slate-50"><span className="font-bold text-red-500">G</span> Google</Button><p className="mt-6 text-center text-sm text-slate-500">New to SkillSwap? <Link className="font-semibold text-indigo-600" to="/register">Create an account</Link></p></Card></AuthLayout> }
