const express = require('express');
const { protect, isAdmin } = require('../middleware/auth');
const { validate } = require('../middleware/validate');
const learning = require('../controllers/learningController');
const assessment = require('../controllers/assessmentController');
const { courseSchema, lectureSchema, attendanceSchema, examSchema, questionSchema, examSubmitSchema, certificateDecisionSchema } = require('../utils/learningValidation');
const router = express.Router();
router.get('/', learning.listCourses);
router.get('/mine/learning', protect, learning.myLearning);
router.get('/mine/teaching', protect, learning.myTeaching);
router.get('/certificate-requests', protect, assessment.listCertificateRequests);
router.patch('/certificate-requests/:requestId/tutor-decision', protect, validate(certificateDecisionSchema), assessment.teacherCertificateDecision);
router.patch('/certificate-requests/:requestId/admin-decision', protect, isAdmin, validate(certificateDecisionSchema), assessment.adminCertificateDecision);
router.get('/certificates/mine', protect, assessment.myCertificates);
router.get('/certificates/verify/:certificateNumber', assessment.verifyCertificate);
router.post('/', protect, validate(courseSchema), learning.createCourse);
router.get('/:courseId', protect, learning.getCourse);
router.patch('/:courseId', protect, validate(courseSchema.partial()), learning.updateCourse);
router.delete('/:courseId', protect, learning.deleteCourse);
router.post('/:courseId/enroll', protect, learning.enroll);
router.delete('/:courseId/enrollment', protect, learning.dropEnrollment);
router.get('/:courseId/lectures', protect, learning.listLectures);
router.post('/:courseId/lectures', protect, validate(lectureSchema), learning.createLecture);
router.patch('/lectures/:lectureId', protect, validate(lectureSchema.partial()), learning.updateLecture);
router.delete('/lectures/:lectureId', protect, learning.deleteLecture);
router.put('/lectures/:lectureId/attendance', protect, validate(attendanceSchema), learning.markAttendance);
router.get('/:courseId/exam', protect, assessment.getCourseExam);
router.post('/:courseId/exam', protect, validate(examSchema), assessment.createExam);
router.patch('/exams/:examId', protect, validate(examSchema.partial()), assessment.updateExam);
router.post('/exams/:examId/questions', protect, validate(questionSchema), assessment.addQuestion);
router.post('/exams/:examId/submit', protect, validate(examSubmitSchema), assessment.submitExam);
router.post('/:courseId/certificate-requests', protect, assessment.requestCertificate);
module.exports = router;
