import { useState } from 'react'
import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { ArrowRight, Check, CirclePlay, Compass, GraduationCap, Menu, MessageCircle, MoveUpRight, Sparkles, Star, UsersRound, X } from 'lucide-react'
import { Avatar, Button } from '../components/ui/Primitives'

const skills = ['Public speaking', 'Illustration', 'Spanish', 'Photography', 'React', 'Pottery', 'Guitar', 'UX research']
const reveal = { hidden: { opacity: 0, y: 24 }, show: { opacity: 1, y: 0 } }

export default function Landing() {
  const [menuOpen, setMenuOpen] = useState(false)
  return <main className="min-h-screen overflow-hidden bg-[#f7f5f2] text-ink">
    <header className="relative z-30 mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8">
      <Link to="/" className="flex items-center gap-2 text-lg font-extrabold"><span className="grid h-9 w-9 place-items-center rounded-full bg-ink text-mint"><Sparkles size={16}/></span>SkillSwap</Link>
      <nav className="hidden items-center gap-7 rounded-full border border-ink/10 bg-white/70 px-5 py-2 text-sm font-bold text-ink/60 backdrop-blur md:flex"><a href="#how" className="hover:text-violet">How it works</a><a href="#why" className="hover:text-violet">Why SkillSwap</a><a href="#community" className="hover:text-violet">Community</a></nav>
      <div className="hidden items-center gap-4 md:flex"><Link to="/login" className="text-sm font-bold text-ink/65 hover:text-ink">Sign in</Link><Link to="/register"><Button className="bg-ink text-white hover:bg-violet">Get started <ArrowRight size={15}/></Button></Link></div>
      <button type="button" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Toggle menu" className="rounded-full border border-ink/10 bg-white p-2.5 md:hidden">{menuOpen?<X size={18}/>:<Menu size={18}/>}</button>
      {menuOpen && <motion.nav initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} className="absolute right-5 top-16 w-56 rounded-2xl border border-ink/10 bg-white p-3 shadow-float md:hidden"><a href="#how" className="block rounded-xl px-3 py-2 text-sm font-bold hover:bg-ink/5">How it works</a><a href="#why" className="block rounded-xl px-3 py-2 text-sm font-bold hover:bg-ink/5">Why SkillSwap</a><Link to="/login" className="block rounded-xl px-3 py-2 text-sm font-bold hover:bg-ink/5">Sign in</Link><Link to="/register" className="mt-2 block rounded-xl bg-ink px-3 py-2 text-center text-sm font-bold text-white">Get started</Link></motion.nav>}
    </header>

    <section className="relative mx-auto max-w-7xl px-5 pb-20 pt-9 sm:px-8 lg:pb-28 lg:pt-16">
      <div className="absolute left-1/2 top-0 -z-10 h-[34rem] w-[34rem] -translate-x-1/2 rounded-full bg-violet/20 blur-[120px]"/>
      <div className="grid gap-12 lg:grid-cols-[1fr_.88fr] lg:items-center">
        <motion.div initial="hidden" animate="show" transition={{staggerChildren:.12}}>
          <motion.p variants={reveal} className="eyebrow inline-flex items-center gap-2 rounded-full border border-violet/20 bg-violet/5 px-3 py-1.5 text-violet"><span className="h-1.5 w-1.5 rounded-full bg-violet animate-pulse"/>Learn from people, not algorithms</motion.p>
          <motion.h1 variants={reveal} className="mt-6 max-w-3xl font-display text-5xl leading-[.94] tracking-tight sm:text-7xl">A more human way to <i className="font-normal text-violet">grow.</i></motion.h1>
          <motion.p variants={reveal} className="mt-7 max-w-xl text-lg leading-8 text-ink/60">Trade your useful knowledge for a skill you’ve been curious about. No money changes hands—just a fair exchange between neighbours.</motion.p>
          <motion.div variants={reveal} className="mt-9 flex flex-wrap gap-3"><Link to="/register"><Button className="bg-ink text-white hover:-translate-y-0.5 hover:bg-violet">Find your next skill <ArrowRight size={16}/></Button></Link><a href="#how" className="action bg-white text-ink shadow-sm ring-1 ring-ink/10 hover:bg-mint"><CirclePlay size={17}/> Watch the idea</a></motion.div>
          <motion.div variants={reveal} className="mt-12 flex items-center gap-4"><div className="flex -space-x-2">{['Lahar Patel','Noah Williams','Sofia Chen','Arjun Rao'].map(name=><span className="rounded-full ring-2 ring-[#f7f5f2]" key={name}><Avatar name={name}/></span>)}</div><div><p className="text-sm font-extrabold">12,486 members swapping skills</p><p className="mt-0.5 text-xs text-ink/45">A little better, together.</p></div></motion.div>
        </motion.div>
        <motion.div initial={{opacity:0,scale:.92,rotate:5}} animate={{opacity:1,scale:1,rotate:0}} transition={{duration:.7,delay:.15,type:'spring'}} className="relative mx-auto h-[410px] w-full max-w-[460px] sm:h-[470px]">
          <div className="absolute inset-8 rounded-[2.5rem] border border-violet/20 bg-violet/5"/>
          <motion.div animate={{y:[0,-10,0],rotate:[-2,0,-2]}} transition={{repeat:Infinity,duration:5,ease:'easeInOut'}} className="absolute left-0 top-12 w-[86%] rounded-[2rem] bg-ink p-6 text-white shadow-float sm:p-7"><div className="flex items-center justify-between"><span className="eyebrow text-mint">Your possible match</span><span className="rounded-full bg-white/10 px-2.5 py-1 text-[10px] font-bold">93% fit</span></div><div className="mt-8 flex items-center gap-4"><span className="grid h-14 w-14 place-items-center rounded-full bg-mint text-xl font-extrabold text-ink">M</span><div><p className="font-display text-3xl">Meera Iyer</p><p className="mt-1 text-sm text-white/60">Speaks Spanish like a local</p></div></div><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/10 p-3"><p className="text-[10px] font-bold text-mint">SHE SHARES</p><p className="mt-1 text-sm font-bold">Spanish</p></div><div className="rounded-2xl bg-white/10 p-3"><p className="text-[10px] font-bold text-mint">YOU SHARE</p><p className="mt-1 text-sm font-bold">Product design</p></div></div><button className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-mint py-3 text-sm font-extrabold text-ink"><MessageCircle size={16}/> Say hello</button></motion.div>
          <motion.div animate={{y:[0,12,0]}} transition={{repeat:Infinity,duration:4.5,ease:'easeInOut'}} className="absolute bottom-5 right-0 w-52 rounded-3xl bg-white p-4 shadow-float"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-full bg-coral/30 text-coral"><Star size={15} className="fill-coral"/></span><p className="text-xs font-bold">A real exchange<br/><span className="font-normal text-ink/45">just happened nearby</span></p></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-ink/10"><motion.i initial={{width:0}} animate={{width:'72%'}} transition={{delay:.8,duration:1.2}} className="block h-full rounded-full bg-violet"/></div></motion.div>
          <span className="absolute right-4 top-2 grid h-16 w-16 place-items-center rounded-full bg-mint text-ink shadow-sm"><MoveUpRight size={26}/></span>
        </motion.div>
      </div>
    </section>

    <section className="overflow-hidden border-y border-ink/10 bg-white py-5"><motion.div initial={{x:'0%'}} animate={{x:'-50%'}} transition={{duration:60,repeat:Infinity,ease:'linear'}} className="flex w-max gap-10 px-5 text-sm font-extrabold text-ink/55">{[...skills,...skills,...skills,...skills].map((skill,index)=><span key={`${skill}-${index}`} className="flex shrink-0 items-center gap-2"><i className="h-2 w-2 rounded-full bg-violet"/>{skill}</span>)}</motion.div></section>

    <section id="how" className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="flex flex-wrap items-end justify-between gap-5"><div className="max-w-2xl"><p className="eyebrow">The exchange, simplified</p><h2 className="mt-3 font-display text-4xl leading-tight sm:text-5xl">It starts with a good question: <i className="font-normal text-violet">what can we teach each other?</i></h2></div><p className="max-w-xs text-sm leading-6 text-ink/55">SkillSwap makes it easy to find the right person, agree on an exchange, and make it happen.</p></div><div className="mt-12 grid gap-4 lg:grid-cols-3">{[['01','Create your little corner','Name the skills you enjoy sharing.'],['02','Meet a great match','Browse people who have what you’re looking for.'],['03','Make it mutual','Propose a swap and schedule your first session.']].map(([number,title,copy],index=0)=><motion.article whileHover={{y:-7}} transition={{type:'spring',stiffness:300}} key={number} className={`group rounded-[2rem] p-7 ${index===1?'bg-mint':'bg-white'}`}><span className="font-mono text-xs font-bold text-violet">{number}</span><span className="mt-16 grid h-12 w-12 place-items-center rounded-2xl bg-ink text-mint transition group-hover:rotate-6">{index===0?<Compass size={21}/>:index===1?<UsersRound size={21}/>:<Check size={21}/>}</span><h3 className="mt-7 font-display text-3xl">{title}</h3><p className="mt-3 max-w-xs text-sm leading-6 text-ink/60">{copy}</p></motion.article>)}</div></section>

    <section id="why" className="bg-ink py-24 text-white"><div className="mx-auto grid max-w-7xl gap-12 px-5 sm:px-8 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="eyebrow text-mint">Why it feels different</p><h2 className="mt-4 font-display text-4xl leading-tight sm:text-5xl">More connection. Less transaction.</h2><p className="mt-6 max-w-md text-base leading-7 text-white/60">A SkillSwap is not a marketplace. It’s a small agreement between two curious people who believe their knowledge has value.</p><Link to="/register" className="mt-8 inline-flex"><Button className="bg-mint text-ink hover:bg-white">Build your profile <ArrowRight size={16}/></Button></Link></div><div className="grid gap-4 sm:grid-cols-2"><motion.div whileHover={{scale:1.02}} className="rounded-3xl bg-white/10 p-6"><p className="font-display text-5xl text-mint">92%</p><p className="mt-3 text-sm leading-6 text-white/65">of members say their exchange helped them feel more connected to their community.</p></motion.div><motion.div whileHover={{scale:1.02}} className="rounded-3xl bg-violet p-6"><GraduationCap size={27} className="text-mint"/><p className="mt-10 font-display text-3xl">Skills are better when they’re shared.</p></motion.div><motion.div whileHover={{scale:1.02}} className="rounded-3xl bg-coral p-6 sm:col-span-2"><div className="flex items-start justify-between gap-5"><p className="max-w-md font-display text-3xl leading-tight">“I taught guitar on Sundays and finally learned the portfolio skills I needed.”</p><span className="hidden rounded-full bg-white/20 p-2 sm:block"><Star className="fill-white"/></span></div><p className="mt-8 text-sm font-bold">Arjun Rao <span className="font-normal text-ink/60">— member since 2024</span></p></motion.div></div></div></section>

    <section id="community" className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="relative overflow-hidden rounded-[2.5rem] bg-mint p-8 sm:p-14"><div className="absolute -right-16 -top-20 h-80 w-80 rounded-full bg-violet/25 blur-3xl"/><div className="relative grid gap-10 lg:grid-cols-[1fr_.65fr] lg:items-end"><div><p className="eyebrow text-ink/60">Ready when you are</p><h2 className="mt-4 max-w-2xl font-display text-5xl leading-[.98]">There’s somebody nearby who can help you make progress.</h2><p className="mt-6 max-w-lg text-base leading-7 text-ink/65">Make a profile, add the skills you can share, and see who you could meet.</p><Link to="/register" className="mt-8 inline-flex"><Button className="bg-ink text-white hover:bg-violet">Join the community <ArrowRight size={16}/></Button></Link></div><div className="rounded-3xl border border-ink/10 bg-white/60 p-5 backdrop-blur"><div className="flex items-center gap-3"><Avatar name="Lahar Patel"/><div><p className="text-sm font-extrabold">Your first profile is 2 minutes away.</p><p className="mt-1 text-xs text-ink/55">And it could lead anywhere.</p></div></div><div className="mt-5 grid grid-cols-3 gap-2">{['Add a skill','Find a match','Start growing'].map((item,index)=><div key={item} className="rounded-xl bg-white p-3 text-center"><span className="grid mx-auto h-5 w-5 place-items-center rounded-full bg-violet text-[10px] font-bold text-white">{index+1}</span><p className="mt-2 text-[10px] font-extrabold leading-4">{item}</p></div>)}</div></div></div></div></section>
    <footer className="border-t border-ink/10 px-5 py-8 text-center text-sm text-ink/45">© 2026 SkillSwap. Learn together, grow together.</footer>
  </main>
}
