import type { ButtonHTMLAttributes, InputHTMLAttributes, ReactNode } from 'react'
import { LoaderCircle, X } from 'lucide-react'

export function Button({ className = '', loading, children, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { loading?: boolean }) { return <button className={`focus-ring inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold transition active:scale-[.98] disabled:cursor-not-allowed disabled:opacity-60 ${className}`} disabled={loading || props.disabled} {...props}>{loading && <LoaderCircle className="h-4 w-4 animate-spin" />}{children}</button> }
export function Input({ className = '', ...props }: InputHTMLAttributes<HTMLInputElement>) { return <input className={`focus-ring w-full rounded-xl border bg-white px-3.5 py-3 text-sm text-slate-800 outline-none placeholder:text-slate-400 transition focus:border-indigo-500 ${className}`} {...props} /> }
export function Card({ children, className = '' }: { children: ReactNode; className?: string }) { return <section className={`rounded-2xl border border-slate-200 bg-white shadow-sm ${className}`}>{children}</section> }
export function Badge({ children, tone = 'slate' }: { children: ReactNode; tone?: 'green'|'amber'|'red'|'blue'|'slate' }) { const tones = { green: 'bg-emerald-50 text-emerald-700', amber: 'bg-amber-50 text-amber-700', red: 'bg-rose-50 text-rose-700', blue: 'bg-indigo-50 text-indigo-700', slate: 'bg-slate-100 text-slate-600' }; return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${tones[tone]}`}>{children}</span> }
export function Avatar({ name, image }: { name: string; image?: string }) { return image ? <img src={image} alt={name} className="h-9 w-9 rounded-full object-cover" /> : <span className="flex h-9 w-9 items-center justify-center rounded-full bg-gradient-to-br from-indigo-500 to-cyan-400 text-xs font-bold text-white">{name.split(' ').map(x => x[0]).slice(0,2).join('')}</span> }
export function Modal({ open, onClose, children }: { open: boolean; onClose: () => void; children: ReactNode }) { if (!open) return null; return <div role="dialog" aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-slate-950/30 p-4 backdrop-blur-sm"><div className="relative w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><button aria-label="Close modal" onClick={onClose} className="focus-ring absolute right-4 top-4 rounded-lg p-1 text-slate-400 hover:bg-slate-100"><X size={18}/></button>{children}</div></div> }
export function EmptyState({ title = 'Nothing here yet' }: { title?: string }) { return <div className="p-10 text-center text-sm text-slate-400">{title}</div> }
export function Skeleton({ className = '' }: { className?: string }) { return <div className={`animate-pulse rounded-lg bg-slate-100 ${className}`} /> }
